ethereum-client:
  image: ethereum/client-go
  volumes:
   - ./data:/root/.ethereum/rinkeby/keystore
  ports:
   - "8545:8545"
   - "30303:30303"
  command: --rinkeby --rpc --rpccorsdomain "*" --rpcaddr 0.0.0.0 --rpcapi "personal,db,eth,net,web3"
  restart: always
